name: Package and Release VS Code Extension

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Go to install-locator
        run: cd install-locator

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Locator
        run: ./install-locator/gradlew runtime -p install-locator

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: install-locator-${{ matrix.os }}
          path: build/image.zip
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          pattern: install-locator-*

      - name: Unzip artifacts
        run: |
          unzip -o install-locator-*.zip

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package

      - name: Upload VSIX to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.vsix'
          tag: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
